name: 'rCTF Deploy Action'
description: 'Opinionated challenge metadata updater for rCTF deployment.'
author: 'b01lers'

branding:
    icon: 'heart'
    color: 'red'

inputs:
    rctf-url:
        description: 'The public URL of the rCTF instance you are deploying to (ex: `http://ctf.b01lers.com:9001`).'
        required: true
    rctf-token:
        description: 'The authentication token of the configured admin account for the rCTF instance.'
        required: true

outputs:
    # N/A

runs:
    using: node20
    main: dist/index.js
