name: 'rCTF Deploy Action'
description: 'Opinionated challenge metadata updater for rCTF deployment.'
author: 'b01lers'

branding:
    icon: 'heart'
    color: 'red'

inputs:
    rctf-url:
        description: 'The public URL of the rCTF instance you are deploying to (ex: `http://ctf.b01lers.com:9001`).'
        required: true
    rctf-token:
        description: 'The authentication token of the configured admin account for the rCTF instance.'
        required: true
    base-dir:
        description: 'The directory to look for challenges in.'
        required: false

outputs:
    deployed:
        description: 'The ids of the deployed challenges.'
    categories:
        description: 'The names of the detected challenge categories.'

runs:
    using: node20
    main: dist/index.js
